syntax = "proto3";

package EngineEvent;

import "shared.proto";


message EVENT_METADATA_SCHEMA {
    string idempotencyKey = 1;
    Shared.ENGINE_EVENT_TYPE type = 2;
}


// actual messages
message DEPTH_UPDATED {
    EVENT_METADATA_SCHEMA metadata = 1;
    Shared.MARKET_ID marketId = 2;
    Shared.DEPTH_INFO depthUpdates = 3;
}

message INDEXPRICE_UPDATED {
    EVENT_METADATA_SCHEMA metadata = 1;
    Shared.MARKET_ID marketId = 2;
    Shared.PRICE price = 3;
}

message LAST_TRADED_PRICE_UPDATED {
    EVENT_METADATA_SCHEMA metadata = 1;
    Shared.MARKET_ID marketId = 2;
    Shared.PRICE price = 3;
}

message TRADES_CREATED {
    EVENT_METADATA_SCHEMA metadata = 1;
    Shared.MARKET_ID marketId = 2;
    repeated Shared.DEPTH_LEVEL trades = 3;
}

message ORDER_CANCELLED {
    EVENT_METADATA_SCHEMA metadata = 1;
    Shared.ORDER_ID orderId = 2;
}

message FUNDING_CREATED {
    EVENT_METADATA_SCHEMA metadata = 1;
    Shared.MARKET_ID marketId = 2;
}

message ORDER_CREATED {
    EVENT_METADATA_SCHEMA metadata = 1;
    Shared.USER_ID userId = 2;
    Shared.ORDER_ID orderId = 3;
    Shared.PRICE price = 4;
    Shared.QTY filledQty = 5;
    Shared.QTY qty = 6;
    Shared.MARGIN margin = 7;
    Shared.MARGIN_TYPE marginType = 8;
    Shared.SIDE side = 9;
    Shared.TYPE type = 10;
    Shared.MARKET_ID marketId = 11;
    Shared.ORDER_STATUS orderStatus = 12;
}

message FILLS_CREATED {
    EVENT_METADATA_SCHEMA metadata = 1;
    Shared.FILL_ID fillId = 2;
    Shared.FILL_ORDER_INFO buyOrderInfo = 3;
    Shared.FILL_ORDER_INFO sellOrderInfo = 4;
    Shared.QTY qty = 5;
    Shared.PRICE price = 6;
    Shared.PRICE bidPrice = 7;
    Shared.MARKET_ID marketId = 8;
}

message ENGINE_EVENT {
    oneof event {
        DEPTH_UPDATED depth_updated = 1;
        INDEXPRICE_UPDATED indexprice_updated = 2;
        LAST_TRADED_PRICE_UPDATED last_traded_price_updated = 3;
        TRADES_CREATED trades_created = 4;
        ORDER_CANCELLED order_cancelled = 5;
        FUNDING_CREATED funding_created = 6;
        ORDER_CREATED order_created = 7;
        FILLS_CREATED fills_created = 8;
    }
}