syntax = "proto3";

import "shared.proto";
import "engineEvent.proto";

package EngineResponse;


message ORDER_SCHEMA {
    Shared.ORDER_INFO info = 1;
    Shared.ORDER_ID orderId = 2;
    Shared.USER_ID userId = 3;
    Shared.QTY filledQty = 4;
    Shared.ORDER_STATUS status = 5;
}

message PRICE_LEVEL_SCHEMA {
    Shared.PRICE price = 1;
    Shared.QTY totalQty = 2;
    repeated ORDER_SCHEMA orders = 3;
}

message ORDERBOOK_SCHEMA {
    repeated PRICE_LEVEL_SCHEMA bids = 1;
    repeated PRICE_LEVEL_SCHEMA asks = 2;
}

message CURRENCY_BALANCE_SCHEMA {
    Shared.CURRENCY_SYMBOL symbol = 1;
    Shared.QTY amount = 2;
}

message POSITION_SCHEMA {
    Shared.POSITION_ID positionId = 1;
    Shared.USER_ID userId = 2;
    Shared.PRICE price = 3;
    Shared.QTY qty = 4;
    Shared.SIDE side = 5;
    Shared.MARKET_ID symbol = 6;
    Shared.MARGIN margin = 7;
    Shared.MARGIN_TYPE marginType = 8;
}

message SYMBOL_POSITION_SCHEMA {
    POSITION_SCHEMA position = 1;
    Shared.MARKET_ID symbol = 2;
}

message FILL_SCHEMA {
    Shared.FILL_ID fillId = 1;
    Shared.MARKET_ID symbol = 2;
    Shared.QTY qty = 3;
    Shared.PRICE price = 4;
    Shared.PRICE bidPrice = 5;
    Shared.FILL_ORDER_INFO sellOrderInfo = 6;
    Shared.FILL_ORDER_INFO buyOrderInfo = 7;
}

message FILLS_SCHEMA {
    repeated FILL_SCHEMA fills = 1;
}

message RESPONSE_METADATA_SCHEMA {
    Shared.REQUEST_ID requestId = 1;
}


// actual messages

message ORDER_CREATED {
    RESPONSE_METADATA_SCHEMA metadata = 1;
    FILLS_SCHEMA fills = 2;
    Shared.ORDER_ID orderId = 3;
    Shared.ORDER_STATUS status = 4;
}

message ORDER_CANCELLED {
    RESPONSE_METADATA_SCHEMA metadata = 1;
    Shared.ORDER_ID orderId = 2;
}

message EVENTS_SUBSCRIBED {
    RESPONSE_METADATA_SCHEMA metadata = 1;
}

message EVENTS_UNSUBSCRIBED {
    RESPONSE_METADATA_SCHEMA metadata = 1;
}

message BALANCE {
    RESPONSE_METADATA_SCHEMA metadata = 1;
    repeated CURRENCY_BALANCE_SCHEMA balance = 2;
}

message BALANCE_UPDATED {
    RESPONSE_METADATA_SCHEMA metadata = 1;
    repeated CURRENCY_BALANCE_SCHEMA balance = 2;
}

message DEPTH {
    RESPONSE_METADATA_SCHEMA metadata = 1;
    Shared.DEPTH_INFO depthInfo = 2;
}

message POSITION {
    RESPONSE_METADATA_SCHEMA metadata = 1;
    repeated SYMBOL_POSITION_SCHEMA position = 2;
}

message ORDERBOOK {
    RESPONSE_METADATA_SCHEMA metadata = 1;
    ORDERBOOK_SCHEMA orderbook = 2;
}

message ERROR {
    RESPONSE_METADATA_SCHEMA metadata = 1;
    string payload = 2;
}

message ENGINE_RESPONSE {
    oneof response {
        ERROR error = 1;
        ORDERBOOK orderbook = 2;
        POSITION position = 3;
        DEPTH depth = 4;
        BALANCE_UPDATED balance_updated = 5;
        BALANCE balance = 6;
        EVENTS_UNSUBSCRIBED events_unsubscribed = 7;
        ORDER_CANCELLED order_cancelled = 8;
        ORDER_CREATED order_created = 9;
        EngineEvent.ENGINE_EVENT event = 10;
        EVENTS_SUBSCRIBED events_subscribed = 11;
    }
}